"""Tests for tools/pitch_fit.py.

READ THIS BEFORE TRUSTING A GREEN RUN. These tests check the ALGEBRA of the
projection the tool inverts, using synthetic profiles generated by that same
projection. They say nothing about whether the tool gets a photograph right --
the pre-flight measured that it does not, reliably, which is why the tool only
proposes. See docs/superpowers/metrics/b4e-preflight-method-rejection.json.

A green run here means the code does what it claims. It does NOT mean a
proposal may be shipped without a named landmark behind it.
"""
import math
import os
import sys

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))

import pitch_fit


def synth_profile(theta_deg, fov_deg, angles_deg, rows=512):
    """A frame whose horizontal edges sit at the given world angles."""
    v = np.zeros(rows - 1)
    half = math.tan(math.radians(fov_deg) / 2.0)
    for a in angles_deg:
        row = 0.5 + 0.5 * math.tan(math.radians(a - theta_deg)) / half
        if 0.0 <= row < 1.0:
            i = int(row * (rows - 1))
            for off, amp in ((-1, 0.5), (0, 1.0), (1, 0.5)):
                if 0 <= i + off < len(v):
                    v[i + off] += amp
    return (v - v.mean()) / (v.std() + 1e-9)


EDGES = [-24.0, -18.0, -11.0, -6.0, -2.0, 3.0, 8.0, 14.0, 19.0, 26.0, 33.0]


def test_recovers_zero_tilt():
    r = pitch_fit.fit(synth_profile(0.0, 72.0, EDGES),
                      synth_profile(0.0, 72.0, EDGES))
    assert abs(r['pitch']) <= 0.5, r


def test_recovers_a_known_tilt():
    r = pitch_fit.fit(synth_profile(22.0, 72.0, EDGES),
                      synth_profile(0.0, 72.0, EDGES))
    assert abs(r['pitch'] - 22.0) <= 0.5, r


# At 40 degrees of tilt a 72-degree frame keeps only world angles 4..76, so
# the EDGES set above leaves the frame and the scenario stops being a test of
# the projection. This set stays visible on BOTH sides. The narrowing itself
# is a real property of the problem, not an artefact: the bigger the tilt, the
# less content a level render and a tilted photograph share -- which is one
# reason a proposal degrades exactly where the tilt is largest.
# Irregularly spaced ON PURPOSE: a uniform ladder is periodic, and a
# correlation against a periodic signal aliases by exactly one period. A
# uniform version of this set returned 30.0 for a true 40.0.
DEEP_EDGES = [5.0, 9.0, 16.0, 22.0, 25.0, 34.0]


def test_recovers_a_large_tilt_outside_the_small_angle_regime():
    """serenity's 2.webp already ships 40 degrees, so the exact projection --
    not a linearised shift -- has to hold out there."""
    r = pitch_fit.fit(synth_profile(40.0, 72.0, DEEP_EDGES),
                      synth_profile(0.0, 72.0, DEEP_EDGES))
    assert abs(r['pitch'] - 40.0) <= 0.5, r


def test_confirmation_pass_returns_the_tilt_the_render_was_captured_at():
    r = pitch_fit.fit(synth_profile(22.0, 72.0, EDGES),
                      synth_profile(22.0, 72.0, EDGES), theta_r_deg=22.0)
    assert abs(r['pitch'] - 22.0) <= 0.5, r


def test_refuses_a_flat_render_with_no_gradient_to_correlate():
    """A featureless render must be refused outright, not scored.

    RENAMED AND STRENGTHENED 2026-08-22 (plan 4e final review, MINOR 5).
    This used to be called `test_refuses_when_nothing_overlaps` and assert
    `r['pitch'] is None or r['overlap'] >= MIN_OVERLAP`, which is satisfied
    BY CONSTRUCTION for any input whatsoever -- `fit` never returns a
    candidate below the floor, because `_score` returns None below it. It
    could not fail. It also never exercised the overlap branch it named: a
    `np.zeros(511)` render trips the zero-variance `denom` guard first. Both
    faults are fixed here -- this test now names what it really covers and
    asserts the refusal itself, and the overlap floor gets its own test
    below.
    """
    photo = synth_profile(0.0, 72.0, [-30.0])
    render = np.zeros(511)
    r = pitch_fit.fit(photo, render)
    assert r['pitch'] is None, r
    assert 'refused' in r, r


def test_refuses_when_no_candidate_keeps_enough_overlap():
    """The MIN_OVERLAP floor, exercised for real -- and it can fail.

    Every candidate tilt in the search is checked against the floor with a
    real, textured render, so nothing here is short-circuited by the
    zero-variance guard. The floor is raised above 1.0 for the duration, so
    NO candidate can satisfy it and `fit` must refuse. With the floor
    removed from `_score` this call returns a pitch and the assert fails --
    which is the property the old test was meant to have and did not.
    """
    photo = synth_profile(0.0, 72.0, EDGES)
    render = synth_profile(0.0, 72.0, EDGES)
    saved = pitch_fit.MIN_OVERLAP
    pitch_fit.MIN_OVERLAP = 1.5
    try:
        r = pitch_fit.fit(photo, render)
    finally:
        pitch_fit.MIN_OVERLAP = saved
    assert r['pitch'] is None, r
    assert r['refused'] == 'no candidate kept enough overlap', r


def test_probe_rejects_a_column_outside_the_frame():
    """--col is a fraction, and an out-of-range one used to return nan.

    Added 2026-08-22 (plan 4e final review, MINOR 6). Before the guard,
    `--col 350` produced an empty strip, two RuntimeWarnings and a table of
    `nan` strengths that read like a measurement.
    """
    img = np.zeros((80, 60), dtype=np.uint8)
    img[40:, :] = 255
    for bad in (-0.1, 1.4, 350):
        try:
            pitch_fit.probe(img, col=bad)
        except ValueError:
            continue
        raise AssertionError('probe accepted col=%r' % (bad,))


def test_remap_rows_is_exact_at_zero_tilt():
    """Identity when nothing moves -- the half-row bias broke this.

    Added 2026-08-22 (plan 4e final review, MINOR 6). With theta_p ==
    theta_r the resampling must be the identity, because every photograph
    row sees exactly the world angle the same render row sees. Under the old
    `idx = v_r * n` the profile came back shifted half a sample and this
    assert fails; under `v_r * n - 0.5` it is exact.
    """
    p = synth_profile(0.0, 72.0, EDGES)
    out, valid = pitch_fit.remap_rows(p, 0.0, 72.0, 0.0)
    assert valid.all()
    assert float(np.abs(out - p).max()) < 1e-9, float(np.abs(out - p).max())


def test_row_profile_is_zero_mean_unit_scale():
    img = np.zeros((200, 120), dtype=np.uint8)
    img[80:, :] = 255
    p = pitch_fit.row_profile(img)
    assert p.shape == (511,)
    assert abs(float(p.mean())) < 1e-6
    assert abs(float(p.std()) - 1.0) < 0.05


def test_probe_finds_a_planted_edge():
    img = np.zeros((400, 200), dtype=np.uint8)
    img[260:, :] = 255                       # one edge at row 260 -> 0.651
    h, rows = pitch_fit.probe(img, col=0.5)
    best = max(rows, key=lambda rs: rs[1])
    assert abs(best[0] / (h - 1.0) - 260 / 399.0) < 0.01, rows


def test_probe_returns_rows_in_order():
    img = np.zeros((400, 200), dtype=np.uint8)
    img[100:, :] = 120
    img[300:, :] = 255
    h, rows = pitch_fit.probe(img, col=0.5)
    assert rows == sorted(rows), rows
