"""Tests for tools/pitch_fit.py.

READ THIS BEFORE TRUSTING A GREEN RUN. These tests check the ALGEBRA of the
projection the tool inverts, using synthetic profiles generated by that same
projection. They say nothing about whether the tool gets a photograph right --
the pre-flight measured that it does not, reliably, which is why the tool only
proposes. See docs/superpowers/metrics/b4e-preflight-method-rejection.json.

A green run here means the code does what it claims. It does NOT mean a
proposal may be shipped without a named landmark behind it.
"""
import math
import os
import sys

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))

import pitch_fit


def synth_profile(theta_deg, fov_deg, angles_deg, rows=512):
    """A frame whose horizontal edges sit at the given world angles."""
    v = np.zeros(rows - 1)
    half = math.tan(math.radians(fov_deg) / 2.0)
    for a in angles_deg:
        row = 0.5 + 0.5 * math.tan(math.radians(a - theta_deg)) / half
        if 0.0 <= row < 1.0:
            i = int(row * (rows - 1))
            for off, amp in ((-1, 0.5), (0, 1.0), (1, 0.5)):
                if 0 <= i + off < len(v):
                    v[i + off] += amp
    return (v - v.mean()) / (v.std() + 1e-9)


EDGES = [-24.0, -18.0, -11.0, -6.0, -2.0, 3.0, 8.0, 14.0, 19.0, 26.0, 33.0]


def test_recovers_zero_tilt():
    r = pitch_fit.fit(synth_profile(0.0, 72.0, EDGES),
                      synth_profile(0.0, 72.0, EDGES))
    assert abs(r['pitch']) <= 0.5, r


def test_recovers_a_known_tilt():
    r = pitch_fit.fit(synth_profile(22.0, 72.0, EDGES),
                      synth_profile(0.0, 72.0, EDGES))
    assert abs(r['pitch'] - 22.0) <= 0.5, r


# At 40 degrees of tilt a 72-degree frame keeps only world angles 4..76, so
# the EDGES set above leaves the frame and the scenario stops being a test of
# the projection. This set stays visible on BOTH sides. The narrowing itself
# is a real property of the problem, not an artefact: the bigger the tilt, the
# less content a level render and a tilted photograph share -- which is one
# reason a proposal degrades exactly where the tilt is largest.
# Irregularly spaced ON PURPOSE: a uniform ladder is periodic, and a
# correlation against a periodic signal aliases by exactly one period. A
# uniform version of this set returned 30.0 for a true 40.0.
DEEP_EDGES = [5.0, 9.0, 16.0, 22.0, 25.0, 34.0]


def test_recovers_a_large_tilt_outside_the_small_angle_regime():
    """serenity's 2.webp already ships 40 degrees, so the exact projection --
    not a linearised shift -- has to hold out there."""
    r = pitch_fit.fit(synth_profile(40.0, 72.0, DEEP_EDGES),
                      synth_profile(0.0, 72.0, DEEP_EDGES))
    assert abs(r['pitch'] - 40.0) <= 0.5, r


def test_confirmation_pass_returns_the_tilt_the_render_was_captured_at():
    r = pitch_fit.fit(synth_profile(22.0, 72.0, EDGES),
                      synth_profile(22.0, 72.0, EDGES), theta_r_deg=22.0)
    assert abs(r['pitch'] - 22.0) <= 0.5, r


def test_refuses_when_nothing_overlaps():
    """A tilt so large the frames share no rows must return no proposal."""
    photo = synth_profile(0.0, 72.0, [-30.0])
    render = np.zeros(511)
    r = pitch_fit.fit(photo, render)
    assert r['pitch'] is None or r['overlap'] >= pitch_fit.MIN_OVERLAP, r


def test_row_profile_is_zero_mean_unit_scale():
    img = np.zeros((200, 120), dtype=np.uint8)
    img[80:, :] = 255
    p = pitch_fit.row_profile(img)
    assert p.shape == (511,)
    assert abs(float(p.mean())) < 1e-6
    assert abs(float(p.std()) - 1.0) < 0.05


def test_probe_finds_a_planted_edge():
    img = np.zeros((400, 200), dtype=np.uint8)
    img[260:, :] = 255                       # one edge at row 260 -> 0.651
    h, rows = pitch_fit.probe(img, col=0.5)
    best = max(rows, key=lambda rs: rs[1])
    assert abs(best[0] / (h - 1.0) - 260 / 399.0) < 0.01, rows


def test_probe_returns_rows_in_order():
    img = np.zeros((400, 200), dtype=np.uint8)
    img[100:, :] = 120
    img[300:, :] = 255
    h, rows = pitch_fit.probe(img, col=0.5)
    assert rows == sorted(rows), rows
